#!/usr/bin/env python3
"""
get_packages.py

Hits the Docassemble API on a running server and writes a requirements.txt of all installed pip packages.
That file can then be copied into a Dockerfile to pre-bake packages into the image at build time instead of runtime.

Usage:
   python3 Docker/get_packages.py \
       --server https://your-server.example.com \
       --api-key YOUR_API_KEY \
       --output Docker/requirements-preinstall.txt
"""
import argparse
import sys
import requests

def fetch_packages(server_url, api_key):
   url = server_url.rstrip("/") + "/api/package"
   headers = {"X-API-Key": api_key}

   print("Connecting to " + server_url)
   r = requests.get(url, headers=headers, timeout=30)

   if r.status_code == 403:
       print("Error: API key rejected.", file=sys.stderr)
       sys.exit(1)

   if r.status_code != 200:
       print("Error: server returned " + str(r.status_code), file=sys.stderr)
       sys.exit(1)

   return r.json()


def build_requirements(packages):
   lines = []

   for pkg in packages:
       name = pkg.get("name", "")
       version = pkg.get("version", "")

       # git packages are server-specific and should not be baked into the image
       if pkg.get("type") == "git":
           continue

       # only handle pip packages from here
       if pkg.get("type") != "pip":
           continue
          
       #skip docassemble core packages - these get installed directly from source
       if name.lower().startswith("docassemble"):
           continue

       # pip itself is not a valid requirements entry
       if name.lower() == "pip":
           continue

       if name and version:
           lines.append(name + "==" + version)

   return sorted(lines)


def write_requirements(lines, output_path, server_url):
   with open(output_path, "w") as f:
       f.write("# Generated by Docker/get_packages.py\n")
       f.write("# Source server: " + server_url + "\n")
       f.write("# Regenerate: python3 Docker/get_packages.py"
               " --server " + server_url +
               " --api-key YOUR_KEY"
               " --output " + output_path + "\n\n")
       for line in lines:
           f.write(line + "\n")


def main():
   parser = argparse.ArgumentParser(
       description="Generate a requirements.txt from a live Docassemble server"
   )
   parser.add_argument("--server", required=True,
                       help="Server URL e.g. https://tf-docassemble-test.suffolklitlab.com")
   parser.add_argument("--api-key", required=True,
                       help="Docassemble API key")
   parser.add_argument("--output", default="Docker/requirements-preinstall.txt",
                       help="Where to write the requirements file")
   args = parser.parse_args()

   packages = fetch_packages(args.server, args.api_key)
   print("Total packages from server: " + str(len(packages)))

   lines = build_requirements(packages)
   print("Writing " + str(len(lines)) + " packages to " + args.output)

   write_requirements(lines, args.output, args.server)
   print("Done.")


if __name__ == "__main__":
   main()