#!/usr/bin/env python3
"""
get_packages.py

Hits the Docassemble API on a running server and writes a requirements.txt
of all installed pip packages. That file can then be copied into a Dockerfile
to pre-bake packages into the image at build time instead of runtime.

Usage:
    python3 Docker/get_packages.py \
        --server https://your-server.example.com \
        --api-key YOUR_API_KEY \
        --output Docker/requirements-preinstall.txt
"""

import argparse
import sys
import requests


# Packages already installed in the Dockerfile with pinned versions.
# Including these in requirements-preinstall.txt would cause version conflicts
DOCKERFILE_PACKAGES = {
    "mod_wsgi",
    "certbot",
    "certbot-apache",
    "certbot-nginx",
    "minio",
    "uwsgi",
    "python-augeas",
}

# These three are installed directly from source in the Dockerfile.
# They don't exist on PyPI as standalone packages.
DOCASSEMBLE_CORE = {
    "docassemble.base",
    "docassemble.demo",
    "docassemble.webapp",
}


def fetch_packages(server_url, api_key):
    url = server_url.rstrip("/") + "/api/package"
    headers = {"X-API-Key": api_key}

    print("Connecting to " + server_url)
    r = requests.get(url, headers=headers, timeout=30)

    if r.status_code == 403:
        print("Error: API key rejected.", file=sys.stderr)
        sys.exit(1)

    if r.status_code != 200:
        print("Error: server returned " + str(r.status_code), file=sys.stderr)
        sys.exit(1)

    return r.json()


def build_requirements(packages):
    lines = []

    for pkg in packages:
        name = pkg.get("name", "")
        version = pkg.get("version", "")
        pkg_type = pkg.get("type", "")

        # skip pip itself
        if name.lower() == "pip":
            continue

        # skip docassemble core packages installed from source
        if name.lower() in DOCASSEMBLE_CORE:
            continue

        # skip packages already pinned in the Dockerfile
        # installing them again would cause version conflicts
        if name.lower() in DOCKERFILE_PACKAGES:
            print("Skipping: " + name)
            continue

        if pkg_type == "git":
            # git packages must be installed with their GitHub URL
            # package name alone won't work for packages not on PyPI
            git_url = pkg.get("git_url", "")
            branch = pkg.get("branch", "")
            if git_url and branch:
                lines.append("git+" + git_url + "@" + branch)
            elif git_url:
                lines.append("git+" + git_url)
            continue

        if pkg_type == "pip" and name and version:
            lines.append(name + "==" + version)

    return sorted(lines)


def write_requirements(lines, output_path, server_url):
    with open(output_path, "w") as f:
        f.write("# Generated by Docker/get_packages.py\n")
        f.write("# Source server: " + server_url + "\n")
        f.write("# Regenerate: python3 Docker/get_packages.py"
                " --server " + server_url +
                " --api-key YOUR_KEY"
                " --output " + output_path + "\n\n")
        for line in lines:
            f.write(line + "\n")


def main():
    parser = argparse.ArgumentParser(
        description="Generate a requirements.txt from a live Docassemble server"
    )
    parser.add_argument("--server", required=True,
                        help="Server URL e.g. https://tf-docassemble-test.suffolklitlab.com")
    parser.add_argument("--api-key", required=True,
                        help="Docassemble API key")
    parser.add_argument("--output", default="Docker/requirements-preinstall.txt",
                        help="Where to write the requirements file")
    args = parser.parse_args()

    packages = fetch_packages(args.server, args.api_key)
    print("Total packages from server: " + str(len(packages)))

    lines = build_requirements(packages)
    print("Writing " + str(len(lines)) + " packages to " + args.output)

    write_requirements(lines, args.output, args.server)
    print("Done.")


if __name__ == "__main__":
    main()